"""create manufacturing

Revision ID: 4066984c07f2
Revises: 5ddeb1ad5ccd
Create Date: 2026-09-27 11:18:49.153092-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

STAFF_PERMISSIONS = ["manufacturing:read", "manufacturing:write"]


revision: str = "4066984c07f2"
down_revision: str | None = "5ddeb1ad5ccd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("yield_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("yield_unit_id", sa.Uuid(), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_recipes_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["yield_unit_id"], ["units.id"], name=op.f("fk_recipes_yield_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipes")),
        sa.UniqueConstraint("product_id", name=op.f("uq_recipes_product_id")),
    )
    op.create_table(
        "production_orders",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("components_warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("target_warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "cancelled", name="production_order_status"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("stock_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["components_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_production_orders_components_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["production_orders.id"],
            name=op.f("fk_production_orders_parent_id_production_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"], ["recipes.id"], name=op.f("fk_production_orders_recipe_id_recipes")
        ),
        sa.ForeignKeyConstraint(
            ["stock_document_id"],
            ["stock_documents.id"],
            name=op.f("fk_production_orders_stock_document_id_stock_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["target_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_production_orders_target_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_orders")),
        sa.UniqueConstraint("number", name=op.f("uq_production_orders_number")),
    )
    op.create_table(
        "recipe_components",
        sa.Column("recipe_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_recipe_components_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
            name=op.f("fk_recipe_components_recipe_id_recipes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_recipe_components_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recipe_components")),
    )
    op.create_index(
        op.f("ix_recipe_components_recipe_id"), "recipe_components", ["recipe_id"], unique=False
    )
    op.create_table(
        "production_order_lines",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["production_orders.id"],
            name=op.f("fk_production_order_lines_order_id_production_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_production_order_lines_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_production_order_lines_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_order_lines")),
    )
    op.create_index(
        op.f("ix_production_order_lines_order_id"),
        "production_order_lines",
        ["order_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    for permission in STAFF_PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission) "
                "SELECT id, :permission FROM roles WHERE code = 'staff'"
            ).bindparams(permission=permission)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_order_lines_order_id"), table_name="production_order_lines")
    op.drop_table("production_order_lines")
    op.drop_index(op.f("ix_recipe_components_recipe_id"), table_name="recipe_components")
    op.drop_table("recipe_components")
    op.drop_table("production_orders")
    op.drop_table("recipes")
    op.execute("DELETE FROM role_permissions WHERE permission LIKE 'manufacturing:%'")
    sa.Enum(name="production_order_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
