"""create inventory

Revision ID: fa5d94c1c109
Revises: fa00067f6f5e
Create Date: 2026-09-27 02:23:59.254859-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Permisos por defecto del rol Administrativo (los ajustes quedan solo para el Dueño)
STAFF_PERMISSIONS = ["inventory:read", "inventory:write", "inventory:cancel"]
ENUMS = ["stock_document_type", "stock_document_status", "stock_cost_mode"]


revision: str = "fa5d94c1c109"
down_revision: str | None = "fa00067f6f5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_sequences",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("last_number", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_document_sequences")),
    )
    op.create_table(
        "stock_documents",
        sa.Column(
            "type",
            sa.Enum(
                "manual_in",
                "manual_out",
                "transfer",
                "adjustment",
                "purchase",
                "sale",
                "consumption",
                "harvest",
                "production",
                name="stock_document_type",
            ),
            nullable=False,
        ),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "cancelled", name="stock_document_status"), nullable=False
        ),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("target_warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("party_id", sa.Uuid(), nullable=True),
        sa.Column("reference", sa.String(length=60), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("source_module", sa.String(length=30), nullable=True),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"], ["parties.id"], name=op.f("fk_stock_documents_party_id_parties")
        ),
        sa.ForeignKeyConstraint(
            ["target_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_documents_target_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_documents_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_documents")),
        sa.UniqueConstraint("number", name=op.f("uq_stock_documents_number")),
    )
    op.create_table(
        "stock_document_lines",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["stock_documents.id"],
            name=op.f("fk_stock_document_lines_document_id_stock_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_document_lines_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_stock_document_lines_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_document_lines")),
    )
    op.create_index(
        op.f("ix_stock_document_lines_document_id"),
        "stock_document_lines",
        ["document_id"],
        unique=False,
    )
    op.create_table(
        "stock_moves",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("sub_no", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cost_mode", sa.Enum("own", "average", name="stock_cost_mode"), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("avg_cost_after", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("cancelled", sa.Boolean(), nullable=False),
        sa.Column("frozen", sa.Boolean(), nullable=False),
        sa.Column("farm_id", sa.Uuid(), nullable=True),
        sa.Column("plot_id", sa.Uuid(), nullable=True),
        sa.Column("crop_cycle_id", sa.Uuid(), nullable=True),
        sa.Column("field_operation_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["stock_documents.id"],
            name=op.f("fk_stock_moves_document_id_stock_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_stock_moves_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"], ["warehouses.id"], name=op.f("fk_stock_moves_warehouse_id_warehouses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_moves")),
    )
    op.create_index("ix_stock_moves_document", "stock_moves", ["document_id"], unique=False)
    op.create_index(
        "ix_stock_moves_product_order",
        "stock_moves",
        ["product_id", "date", "document_id", "line_no", "sub_no"],
        unique=False,
    )
    op.create_index(
        "ix_stock_moves_product_warehouse",
        "stock_moves",
        ["product_id", "warehouse_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    for permission in STAFF_PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission) "
                "SELECT id, :permission FROM roles WHERE code = 'staff'"
            ).bindparams(permission=permission)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_moves_product_warehouse", table_name="stock_moves")
    op.drop_index("ix_stock_moves_product_order", table_name="stock_moves")
    op.drop_index("ix_stock_moves_document", table_name="stock_moves")
    op.drop_table("stock_moves")
    op.drop_index(op.f("ix_stock_document_lines_document_id"), table_name="stock_document_lines")
    op.drop_table("stock_document_lines")
    op.drop_table("stock_documents")
    op.drop_table("document_sequences")
    op.execute("DELETE FROM role_permissions WHERE permission LIKE 'inventory:%'")
    for enum_name in ENUMS:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
