"""create masterdata

Revision ID: fa00067f6f5e
Revises: 37901fc9d62a
Create Date: 2026-09-27 01:52:09.387486-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from uuid6 import uuid7

# (código, nombre, tipo, factor respecto de la unidad base del tipo)
UNITS = [
    ("kg", "Kilogramo", "mass", 1),
    ("g", "Gramo", "mass", 0.001),
    ("tn", "Tonelada", "mass", 1000),
    ("L", "Litro", "volume", 1),
    ("mL", "Mililitro", "volume", 0.001),
    ("m³", "Metro cúbico", "volume", 1000),
    ("un", "Unidad", "count", 1),
    ("h", "Hora", "time", 1),
    ("km", "Kilómetro", "distance", 1),
    ("ha", "Hectárea", "area", 1),
    ("cajón", "Cajón", "package", 1),
    ("bin", "Bin", "package", 1),
    ("bidón", "Bidón", "package", 1),
]

# Categorías iniciales (el cliente las edita): {padre: [hijas]}
CATEGORIES = {
    "Insumos": [
        "Agroquímicos",
        "Fertilizantes",
        "Semillas y plantines",
        "Combustibles y lubricantes",
        "Repuestos",
    ],
    "Producción propia": ["Frutas", "Hortalizas", "Madera"],
    "Elaborados": [],
    "Reventa": [],
    "Servicios": [],
}

STAFF_PERMISSIONS = ["masterdata:read", "masterdata:write", "masterdata:deactivate"]
ENUMS = ["unit_kind", "product_type", "vat_condition", "warehouse_kind"]


revision: str = "fa00067f6f5e"
down_revision: str | None = "37901fc9d62a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parties",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("trade_name", sa.String(length=150), nullable=False),
        sa.Column("cuit", sa.String(length=11), nullable=True),
        sa.Column(
            "vat_condition",
            sa.Enum(
                "registered",
                "monotax",
                "exempt",
                "final_consumer",
                "not_registered",
                name="vat_condition",
            ),
            nullable=False,
        ),
        sa.Column("is_customer", sa.Boolean(), nullable=False),
        sa.Column("is_supplier", sa.Boolean(), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("province", sa.String(length=60), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("payment_days", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parties")),
        sa.UniqueConstraint("cuit", name=op.f("uq_parties_cuit")),
    )
    op.create_table(
        "product_categories",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product_categories.id"],
            name=op.f("fk_product_categories_parent_id_product_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
    )
    op.create_table(
        "units",
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "mass", "volume", "count", "time", "distance", "area", "package", name="unit_kind"
            ),
            nullable=False,
        ),
        sa.Column("factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units")),
        sa.UniqueConstraint("code", name=op.f("uq_units_code")),
    )
    op.create_table(
        "warehouses",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "depot", "cold_storage", "shed", "agrochemicals", "other", name="warehouse_kind"
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("name", name=op.f("uq_warehouses_name")),
    )
    op.create_table(
        "products",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "input",
                "semi_finished",
                "finished",
                "own_produce",
                "resale",
                "service",
                name="product_type",
            ),
            nullable=False,
        ),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("min_stock", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
            name=op.f("fk_products_category_id_product_categories"),
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], name=op.f("fk_products_unit_id_units")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("code", name=op.f("uq_products_code")),
    )
    op.create_table(
        "product_unit_conversions",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_unit_conversions_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_product_unit_conversions_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_unit_conversions")),
    )
    # ### end Alembic commands ###
    _seed()


def _seed() -> None:
    units = sa.table(
        "units",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("kind", sa.Enum(name="unit_kind")),
        sa.column("factor", sa.Numeric()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(
        units,
        [
            {"id": uuid7(), "code": c, "name": n, "kind": k, "factor": f, "is_active": True}
            for c, n, k, f in UNITS
        ],
    )

    categories = sa.table(
        "product_categories",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("parent_id", sa.Uuid()),
        sa.column("is_active", sa.Boolean()),
    )
    rows = []
    for parent, children in CATEGORIES.items():
        parent_id = uuid7()
        rows.append({"id": parent_id, "name": parent, "parent_id": None, "is_active": True})
        rows += [
            {"id": uuid7(), "name": child, "parent_id": parent_id, "is_active": True}
            for child in children
        ]
    op.bulk_insert(categories, rows)

    # Permisos por defecto del rol Administrativo
    for permission in STAFF_PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission) "
                "SELECT id, :permission FROM roles WHERE code = 'staff'"
            ).bindparams(permission=permission)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_unit_conversions")
    op.drop_table("products")
    op.drop_table("warehouses")
    op.drop_table("units")
    op.drop_table("product_categories")
    op.drop_table("parties")
    op.execute("DELETE FROM role_permissions WHERE permission LIKE 'masterdata:%'")
    for enum_name in ENUMS:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
