"""create production and assets

Revision ID: 5ddeb1ad5ccd
Revises: cc193ffc8082
Create Date: 2026-09-27 02:54:05.626524-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from uuid6 import uuid7

# Tipos de labor iniciales: (nombre, lleva insumos, lleva maquinaria, es cosecha)
OPERATION_TYPES = [
    ("Preparación de suelo", False, True, False),
    ("Siembra", True, True, False),
    ("Trasplante", True, True, False),
    ("Plantación", True, True, False),
    ("Aplicación", True, True, False),
    ("Fertilización", True, True, False),
    ("Riego", True, True, False),
    ("Poda", False, True, False),
    ("Raleo", False, True, False),
    ("Desmalezado", True, True, False),
    ("Cosecha", False, True, True),
    ("Tala", False, True, True),
]

STAFF_PERMISSIONS = [
    "production:read",
    "production:write",
    "production:config",
    "assets:read",
    "assets:write",
]
ENUMS = [
    "asset_kind",
    "asset_meter",
    "asset_status",
    "plot_kind",
    "crop_kind",
    "cycle_status",
    "field_operation_status",
]


revision: str = "5ddeb1ad5ccd"
down_revision: str | None = "cc193ffc8082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "kind", sa.Enum("machinery", "vehicle", "tool", name="asset_kind"), nullable=False
        ),
        sa.Column("brand", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=60), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("identifier", sa.String(length=40), nullable=False),
        sa.Column("meter", sa.Enum("hours", "km", name="asset_meter"), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "status", sa.Enum("operational", "in_repair", name="asset_status"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("name", name=op.f("uq_assets_name")),
    )
    op.create_table(
        "farms",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("area_ha", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_farms")),
        sa.UniqueConstraint("name", name=op.f("uq_farms_name")),
    )
    op.create_table(
        "operation_types",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("uses_inputs", sa.Boolean(), nullable=False),
        sa.Column("uses_assets", sa.Boolean(), nullable=False),
        sa.Column("is_harvest", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_types")),
        sa.UniqueConstraint("name", name=op.f("uq_operation_types_name")),
    )
    op.create_table(
        "seasons",
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint("name", name=op.f("uq_seasons_name")),
    )
    op.create_table(
        "plots",
        sa.Column("farm_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("area_ha", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "kind", sa.Enum("open_field", "greenhouse", "forest", name="plot_kind"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["farm_id"], ["farms.id"], name=op.f("fk_plots_farm_id_farms")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plots")),
        sa.UniqueConstraint("farm_id", "name", name=op.f("uq_plots_farm_id")),
    )
    op.create_table(
        "crops",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("species", sa.String(length=60), nullable=False),
        sa.Column("variety", sa.String(length=60), nullable=False),
        sa.Column(
            "kind", sa.Enum("fruit", "vegetable", "forest", name="crop_kind"), nullable=False
        ),
        sa.Column("harvest_product_id", sa.Uuid(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["harvest_product_id"],
            ["products.id"],
            name=op.f("fk_crops_harvest_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crops")),
        sa.UniqueConstraint("name", name=op.f("uq_crops_name")),
    )
    op.create_table(
        "field_operations",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("operation_type_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "cancelled", name="field_operation_status"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("total_area_ha", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stock_document_id", sa.Uuid(), nullable=True),
        sa.Column("harvest_product_id", sa.Uuid(), nullable=True),
        sa.Column("harvest_unit_id", sa.Uuid(), nullable=True),
        sa.Column("harvest_quantity", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("harvest_warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("is_final_harvest", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["harvest_product_id"],
            ["products.id"],
            name=op.f("fk_field_operations_harvest_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["harvest_unit_id"],
            ["units.id"],
            name=op.f("fk_field_operations_harvest_unit_id_units"),
        ),
        sa.ForeignKeyConstraint(
            ["harvest_warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_field_operations_harvest_warehouse_id_warehouses"),
        ),
        sa.ForeignKeyConstraint(
            ["operation_type_id"],
            ["operation_types.id"],
            name=op.f("fk_field_operations_operation_type_id_operation_types"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_document_id"],
            ["stock_documents.id"],
            name=op.f("fk_field_operations_stock_document_id_stock_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_operations")),
        sa.UniqueConstraint("number", name=op.f("uq_field_operations_number")),
    )
    op.create_index("ix_field_operations_date", "field_operations", ["date"], unique=False)
    op.create_table(
        "crop_cycles",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("plot_id", sa.Uuid(), nullable=False),
        sa.Column("crop_id", sa.Uuid(), nullable=False),
        sa.Column("season_id", sa.Uuid(), nullable=False),
        sa.Column("area_ha", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("expected_end_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.Enum("active", "finished", name="cycle_status"), nullable=False),
        sa.Column("reopen_reason", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop_id"], ["crops.id"], name=op.f("fk_crop_cycles_crop_id_crops")
        ),
        sa.ForeignKeyConstraint(
            ["plot_id"], ["plots.id"], name=op.f("fk_crop_cycles_plot_id_plots")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_crop_cycles_season_id_seasons")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crop_cycles")),
    )
    op.create_index(
        "ix_crop_cycles_plot_status", "crop_cycles", ["plot_id", "status"], unique=False
    )
    op.create_table(
        "field_operation_assets",
        sa.Column("field_operation_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("usage", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("rate", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_field_operation_assets_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["field_operation_id"],
            ["field_operations.id"],
            name=op.f("fk_field_operation_assets_field_operation_id_field_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_operation_assets")),
    )
    op.create_index(
        op.f("ix_field_operation_assets_asset_id"),
        "field_operation_assets",
        ["asset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_operation_assets_field_operation_id"),
        "field_operation_assets",
        ["field_operation_id"],
        unique=False,
    )
    op.create_table(
        "field_operation_inputs",
        sa.Column("field_operation_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("dose_per_ha", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["field_operation_id"],
            ["field_operations.id"],
            name=op.f("fk_field_operation_inputs_field_operation_id_field_operations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_field_operation_inputs_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_field_operation_inputs_unit_id_units")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_field_operation_inputs_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_operation_inputs")),
    )
    op.create_index(
        op.f("ix_field_operation_inputs_field_operation_id"),
        "field_operation_inputs",
        ["field_operation_id"],
        unique=False,
    )
    op.create_table(
        "batches",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("crop_cycle_id", sa.Uuid(), nullable=False),
        sa.Column("field_operation_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop_cycle_id"], ["crop_cycles.id"], name=op.f("fk_batches_crop_cycle_id_crop_cycles")
        ),
        sa.ForeignKeyConstraint(
            ["field_operation_id"],
            ["field_operations.id"],
            name=op.f("fk_batches_field_operation_id_field_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_batches_product_id_products")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_batches")),
        sa.UniqueConstraint("code", name=op.f("uq_batches_code")),
    )
    op.create_index(op.f("ix_batches_crop_cycle_id"), "batches", ["crop_cycle_id"], unique=False)
    op.create_table(
        "field_operation_cycles",
        sa.Column("field_operation_id", sa.Uuid(), nullable=False),
        sa.Column("crop_cycle_id", sa.Uuid(), nullable=False),
        sa.Column("area_ha", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop_cycle_id"],
            ["crop_cycles.id"],
            name=op.f("fk_field_operation_cycles_crop_cycle_id_crop_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["field_operation_id"],
            ["field_operations.id"],
            name=op.f("fk_field_operation_cycles_field_operation_id_field_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_operation_cycles")),
    )
    op.create_index(
        op.f("ix_field_operation_cycles_crop_cycle_id"),
        "field_operation_cycles",
        ["crop_cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_operation_cycles_field_operation_id"),
        "field_operation_cycles",
        ["field_operation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_stock_moves_batch_id"), "stock_moves", ["batch_id"], unique=False)
    op.create_index(
        op.f("ix_stock_moves_crop_cycle_id"), "stock_moves", ["crop_cycle_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_moves_field_operation_id"),
        "stock_moves",
        ["field_operation_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_batch_id_batches"), "stock_moves", "batches", ["batch_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_plot_id_plots"), "stock_moves", "plots", ["plot_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_field_operation_id_field_operations"),
        "stock_moves",
        "field_operations",
        ["field_operation_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_farm_id_farms"), "stock_moves", "farms", ["farm_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_asset_id_assets"), "stock_moves", "assets", ["asset_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_stock_moves_crop_cycle_id_crop_cycles"),
        "stock_moves",
        "crop_cycles",
        ["crop_cycle_id"],
        ["id"],
    )
    # ### end Alembic commands ###
    operation_types = sa.table(
        "operation_types",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("uses_inputs", sa.Boolean()),
        sa.column("uses_assets", sa.Boolean()),
        sa.column("is_harvest", sa.Boolean()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(
        operation_types,
        [
            {
                "id": uuid7(),
                "name": name,
                "uses_inputs": inputs,
                "uses_assets": assets,
                "is_harvest": harvest,
                "is_active": True,
            }
            for name, inputs, assets, harvest in OPERATION_TYPES
        ],
    )
    for permission in STAFF_PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission) "
                "SELECT id, :permission FROM roles WHERE code = 'staff'"
            ).bindparams(permission=permission)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_stock_moves_crop_cycle_id_crop_cycles"), "stock_moves", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_stock_moves_asset_id_assets"), "stock_moves", type_="foreignkey")
    op.drop_constraint(op.f("fk_stock_moves_farm_id_farms"), "stock_moves", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_stock_moves_field_operation_id_field_operations"),
        "stock_moves",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("fk_stock_moves_plot_id_plots"), "stock_moves", type_="foreignkey")
    op.drop_constraint(op.f("fk_stock_moves_batch_id_batches"), "stock_moves", type_="foreignkey")
    op.drop_index(op.f("ix_stock_moves_field_operation_id"), table_name="stock_moves")
    op.drop_index(op.f("ix_stock_moves_crop_cycle_id"), table_name="stock_moves")
    op.drop_index(op.f("ix_stock_moves_batch_id"), table_name="stock_moves")
    op.drop_index(
        op.f("ix_field_operation_cycles_field_operation_id"), table_name="field_operation_cycles"
    )
    op.drop_index(
        op.f("ix_field_operation_cycles_crop_cycle_id"), table_name="field_operation_cycles"
    )
    op.drop_table("field_operation_cycles")
    op.drop_index(op.f("ix_batches_crop_cycle_id"), table_name="batches")
    op.drop_table("batches")
    op.drop_index(
        op.f("ix_field_operation_inputs_field_operation_id"), table_name="field_operation_inputs"
    )
    op.drop_table("field_operation_inputs")
    op.drop_index(
        op.f("ix_field_operation_assets_field_operation_id"), table_name="field_operation_assets"
    )
    op.drop_index(op.f("ix_field_operation_assets_asset_id"), table_name="field_operation_assets")
    op.drop_table("field_operation_assets")
    op.drop_index("ix_crop_cycles_plot_status", table_name="crop_cycles")
    op.drop_table("crop_cycles")
    op.drop_index("ix_field_operations_date", table_name="field_operations")
    op.drop_table("field_operations")
    op.drop_table("crops")
    op.drop_table("plots")
    op.drop_table("seasons")
    op.drop_table("operation_types")
    op.drop_table("farms")
    op.drop_table("assets")
    op.execute(
        "DELETE FROM role_permissions WHERE permission LIKE 'production:%' "
        "OR permission LIKE 'assets:%'"
    )
    for enum_name in ENUMS:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
