"""add opening balance flag

Revision ID: 97cfa092b71f
Revises: 2bad85cd885b
Create Date: 2026-09-27 17:50:49.755725-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "97cfa092b71f"
down_revision: str | None = "2bad85cd885b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commercial_documents",
        sa.Column("is_opening_balance", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commercial_documents", "is_opening_balance")
    # ### end Alembic commands ###
