"""create commercial and cash

Revision ID: 30bb03d76daf
Revises: ba9f551735f9
Create Date: 2026-09-27 12:11:48.112351-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
from uuid6 import uuid7

revision: str = "30bb03d76daf"
down_revision: str | None = "ba9f551735f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Varios tipos se usan en más de una tabla: se crean una sola vez acá.
ENUMS = {
    "cash_account_kind": ("cash", "bank"),
    "commercial_direction": ("purchase", "sale"),
    "commercial_document_kind": ("invoice", "credit_note", "debit_note"),
    "commercial_status": ("active", "cancelled"),
    "commercial_line_kind": ("product", "expense"),
    "payment_method": ("cash", "transfer"),
    "cash_movement_kind": ("income", "expense", "withdrawal", "transfer"),
}
EXPENSE_CATEGORIES = (
    "Combustible",
    "Reparaciones y repuestos",
    "Servicios contratados",
    "Fletes",
    "Energía eléctrica",
    "Impuestos y tasas",
    "Seguros",
    "Comisiones y gastos bancarios",
    "Honorarios",
    "Alquileres",
    "Otros gastos",
)
STAFF_PERMISSIONS = (
    "commercial:read",
    "commercial:write",
    "commercial:cancel",
    "cash:read",
    "cash:write",
)


def upgrade() -> None:
    for name, values in ENUMS.items():
        ENUM(*values, name=name).create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cash_accounts",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            ENUM("cash", "bank", name="cash_account_kind", create_type=False),
            nullable=False,
        ),
        sa.Column("opening_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("opening_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_accounts")),
        sa.UniqueConstraint("name", name=op.f("uq_cash_accounts_name")),
    )
    op.create_table(
        "expense_categories",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expense_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_expense_categories_name")),
    )
    op.create_table(
        "payments",
        sa.Column(
            "direction",
            ENUM("purchase", "sale", name="commercial_direction", create_type=False),
            nullable=False,
        ),
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "status",
            ENUM("active", "cancelled", name="commercial_status", create_type=False),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"], ["parties.id"], name=op.f("fk_payments_party_id_parties")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("number", name=op.f("uq_payments_number")),
    )
    op.create_index("ix_payments_party", "payments", ["party_id", "direction"], unique=False)
    op.create_table(
        "commercial_documents",
        sa.Column(
            "direction",
            ENUM("purchase", "sale", name="commercial_direction", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "kind",
            ENUM(
                "invoice",
                "credit_note",
                "debit_note",
                name="commercial_document_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("internal_number", sa.String(length=20), nullable=False),
        sa.Column("has_invoice", sa.Boolean(), nullable=False),
        sa.Column("letter", sa.String(length=1), nullable=False),
        sa.Column("pos_number", sa.String(length=5), nullable=False),
        sa.Column("number", sa.String(length=8), nullable=False),
        sa.Column("party_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            ENUM("active", "cancelled", name="commercial_status", create_type=False),
            nullable=False,
        ),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("net_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("vat_total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("other_taxes", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("stock_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"], ["parties.id"], name=op.f("fk_commercial_documents_party_id_parties")
        ),
        sa.ForeignKeyConstraint(
            ["stock_document_id"],
            ["stock_documents.id"],
            name=op.f("fk_commercial_documents_stock_document_id_stock_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_commercial_documents_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commercial_documents")),
        sa.UniqueConstraint(
            "internal_number", name=op.f("uq_commercial_documents_internal_number")
        ),
    )
    op.create_index(
        "ix_commercial_documents_party",
        "commercial_documents",
        ["party_id", "direction"],
        unique=False,
    )
    op.create_table(
        "payment_lines",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            ENUM("cash", "transfer", name="payment_method", create_type=False),
            nullable=False,
        ),
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reference", sa.String(length=60), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_payment_lines_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_payment_lines_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_lines")),
    )
    op.create_index(
        op.f("ix_payment_lines_cash_account_id"), "payment_lines", ["cash_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_lines_payment_id"), "payment_lines", ["payment_id"], unique=False
    )
    op.create_table(
        "allocations",
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["commercial_documents.id"],
            name=op.f("fk_allocations_document_id_commercial_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
            name=op.f("fk_allocations_payment_id_payments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(
        op.f("ix_allocations_document_id"), "allocations", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_allocations_payment_id"), "allocations", ["payment_id"], unique=False)
    op.create_table(
        "cash_movements",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "kind",
            ENUM(
                "income",
                "expense",
                "withdrawal",
                "transfer",
                name="cash_movement_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("cash_account_id", sa.Uuid(), nullable=False),
        sa.Column("target_account_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("expense_category_id", sa.Uuid(), nullable=True),
        sa.Column("farm_id", sa.Uuid(), nullable=True),
        sa.Column("plot_id", sa.Uuid(), nullable=True),
        sa.Column("crop_cycle_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            ENUM("active", "cancelled", name="commercial_status", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_cash_movements_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["cash_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_cash_movements_cash_account_id_cash_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["crop_cycle_id"],
            ["crop_cycles.id"],
            name=op.f("fk_cash_movements_crop_cycle_id_crop_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expense_categories.id"],
            name=op.f("fk_cash_movements_expense_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"], ["farms.id"], name=op.f("fk_cash_movements_farm_id_farms")
        ),
        sa.ForeignKeyConstraint(
            ["plot_id"], ["plots.id"], name=op.f("fk_cash_movements_plot_id_plots")
        ),
        sa.ForeignKeyConstraint(
            ["target_account_id"],
            ["cash_accounts.id"],
            name=op.f("fk_cash_movements_target_account_id_cash_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_movements")),
        sa.UniqueConstraint("number", name=op.f("uq_cash_movements_number")),
    )
    op.create_index(
        op.f("ix_cash_movements_cash_account_id"),
        "cash_movements",
        ["cash_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cash_movements_crop_cycle_id"), "cash_movements", ["crop_cycle_id"], unique=False
    )
    op.create_table(
        "commercial_lines",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            ENUM("product", "expense", name="commercial_line_kind", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("unit_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=True),
        sa.Column("expense_category_id", sa.Uuid(), nullable=True),
        sa.Column("farm_id", sa.Uuid(), nullable=True),
        sa.Column("plot_id", sa.Uuid(), nullable=True),
        sa.Column("crop_cycle_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("vat_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_commercial_lines_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name=op.f("fk_commercial_lines_batch_id_batches")
        ),
        sa.ForeignKeyConstraint(
            ["crop_cycle_id"],
            ["crop_cycles.id"],
            name=op.f("fk_commercial_lines_crop_cycle_id_crop_cycles"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["commercial_documents.id"],
            name=op.f("fk_commercial_lines_document_id_commercial_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["expense_category_id"],
            ["expense_categories.id"],
            name=op.f("fk_commercial_lines_expense_category_id_expense_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["farm_id"], ["farms.id"], name=op.f("fk_commercial_lines_farm_id_farms")
        ),
        sa.ForeignKeyConstraint(
            ["plot_id"], ["plots.id"], name=op.f("fk_commercial_lines_plot_id_plots")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_commercial_lines_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_commercial_lines_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commercial_lines")),
    )
    op.create_index(
        op.f("ix_commercial_lines_asset_id"), "commercial_lines", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_commercial_lines_crop_cycle_id"),
        "commercial_lines",
        ["crop_cycle_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_commercial_lines_document_id"), "commercial_lines", ["document_id"], unique=False
    )
    # ### end Alembic commands ###
    categories = sa.table(
        "expense_categories",
        sa.column("id", sa.Uuid()),
        sa.column("name", sa.String()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(
        categories, [{"id": uuid7(), "name": n, "is_active": True} for n in EXPENSE_CATEGORIES]
    )
    for permission in STAFF_PERMISSIONS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission) "
                "SELECT id, :permission FROM roles WHERE code = 'staff'"
            ).bindparams(permission=permission)
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_commercial_lines_document_id"), table_name="commercial_lines")
    op.drop_index(op.f("ix_commercial_lines_crop_cycle_id"), table_name="commercial_lines")
    op.drop_index(op.f("ix_commercial_lines_asset_id"), table_name="commercial_lines")
    op.drop_table("commercial_lines")
    op.drop_index(op.f("ix_cash_movements_crop_cycle_id"), table_name="cash_movements")
    op.drop_index(op.f("ix_cash_movements_cash_account_id"), table_name="cash_movements")
    op.drop_table("cash_movements")
    op.drop_index(op.f("ix_allocations_payment_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_document_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_payment_lines_payment_id"), table_name="payment_lines")
    op.drop_index(op.f("ix_payment_lines_cash_account_id"), table_name="payment_lines")
    op.drop_table("payment_lines")
    op.drop_index("ix_commercial_documents_party", table_name="commercial_documents")
    op.drop_table("commercial_documents")
    op.drop_index("ix_payments_party", table_name="payments")
    op.drop_table("payments")
    op.drop_table("expense_categories")
    op.drop_table("cash_accounts")
    op.execute(
        "DELETE FROM role_permissions WHERE permission LIKE 'commercial:%' "
        "OR permission LIKE 'cash:%'"
    )
    for name in ENUMS:
        ENUM(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
