"""add related document

Revision ID: b5af1794de64
Revises: 30bb03d76daf
Create Date: 2026-09-27 12:46:03.929550-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "b5af1794de64"
down_revision: str | None = "30bb03d76daf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "commercial_documents", sa.Column("related_document_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_commercial_documents_related_document_id"),
        "commercial_documents",
        ["related_document_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_commercial_documents_related_document_id_commercial_documents"),
        "commercial_documents",
        "commercial_documents",
        ["related_document_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_commercial_documents_related_document_id_commercial_documents"),
        "commercial_documents",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_commercial_documents_related_document_id"), table_name="commercial_documents"
    )
    op.drop_column("commercial_documents", "related_document_id")
    # ### end Alembic commands ###
