"""add asset maintenance

Revision ID: 2bad85cd885b
Revises: b5af1794de64
Create Date: 2026-09-27 13:42:46.777879-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "2bad85cd885b"
down_revision: str | None = "b5af1794de64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset_meter_readings",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=12, scale=1), nullable=False),
        sa.Column("notes", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_asset_meter_readings_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_meter_readings")),
    )
    op.create_index(
        op.f("ix_asset_meter_readings_asset_id"), "asset_meter_readings", ["asset_id"], unique=False
    )
    op.create_table(
        "maintenance_plans",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("every_usage", sa.Numeric(precision=12, scale=1), nullable=True),
        sa.Column("every_months", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_reading", sa.Numeric(precision=12, scale=1), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_maintenance_plans_asset_id_assets")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_plans")),
    )
    op.create_index(
        op.f("ix_maintenance_plans_asset_id"), "maintenance_plans", ["asset_id"], unique=False
    )
    op.create_table(
        "maintenances",
        sa.Column("number", sa.String(length=20), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "kind", sa.Enum("preventive", "corrective", name="maintenance_kind"), nullable=False
        ),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("meter_reading", sa.Numeric(precision=12, scale=1), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.Enum("active", "cancelled", name="maintenance_status"), nullable=False
        ),
        sa.Column("stock_document_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_maintenances_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["maintenance_plans.id"],
            name=op.f("fk_maintenances_plan_id_maintenance_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["purchase_document_id"],
            ["commercial_documents.id"],
            name=op.f("fk_maintenances_purchase_document_id_commercial_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["stock_document_id"],
            ["stock_documents.id"],
            name=op.f("fk_maintenances_stock_document_id_stock_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_maintenances_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenances")),
        sa.UniqueConstraint("number", name=op.f("uq_maintenances_number")),
    )
    op.create_index(op.f("ix_maintenances_asset_id"), "maintenances", ["asset_id"], unique=False)
    op.create_index(op.f("ix_maintenances_plan_id"), "maintenances", ["plan_id"], unique=False)
    op.create_table(
        "maintenance_parts",
        sa.Column("maintenance_id", sa.Uuid(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["maintenance_id"],
            ["maintenances.id"],
            name=op.f("fk_maintenance_parts_maintenance_id_maintenances"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("fk_maintenance_parts_product_id_products")
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"], ["units.id"], name=op.f("fk_maintenance_parts_unit_id_units")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maintenance_parts")),
    )
    op.create_index(
        op.f("ix_maintenance_parts_maintenance_id"),
        "maintenance_parts",
        ["maintenance_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenance_parts_maintenance_id"), table_name="maintenance_parts")
    op.drop_table("maintenance_parts")
    op.drop_index(op.f("ix_maintenances_plan_id"), table_name="maintenances")
    op.drop_index(op.f("ix_maintenances_asset_id"), table_name="maintenances")
    op.drop_table("maintenances")
    op.drop_index(op.f("ix_maintenance_plans_asset_id"), table_name="maintenance_plans")
    op.drop_table("maintenance_plans")
    op.drop_index(op.f("ix_asset_meter_readings_asset_id"), table_name="asset_meter_readings")
    op.drop_table("asset_meter_readings")
    for name in ("maintenance_kind", "maintenance_status"):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
