"""add login events

Revision ID: ff39a7910a0c
Revises: 97cfa092b71f
Create Date: 2026-09-27 21:59:51.661599-03:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "ff39a7910a0c"
down_revision: str | None = "97cfa092b71f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_events",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.String(length=200), nullable=False),
        sa.Column(
            "result",
            sa.Enum("success", "failed", "locked", "blocked_ip", name="login_result"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_login_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_events")),
    )
    op.create_index(
        "ix_login_events_ip_created", "login_events", ["ip", "created_at"], unique=False
    )
    op.create_index(op.f("ix_login_events_user_id"), "login_events", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_login_events_user_id"), table_name="login_events")
    op.drop_index("ix_login_events_ip_created", table_name="login_events")
    op.drop_table("login_events")
    sa.Enum(name="login_result").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
